# global path files
---
global:
  armors: !include items/armors.yml
  weapons: !include items/weapons.yml
  items: config/items/items.yml
  consumables: config/items/consumables.yml
  gems: config/items/gems.yml
town shop:
  armors: config/town/armors.yml
  weapons: config/town/weapons.yml
  items: config/town/items.yml
  consumables: config/town/consumables.yml
  gems: config/town/gems.yml
  
#- &test_item
#  name: item name
#  lore: description
#  weight: !!int 1
#  lvl: !!int 1

# Town shop items