# Paths of all the weapons of the game
---
double handed:
  large swords: weapons/long_swords.yml
  axes: weapons/axes.yml
  staves: weapons/staves.yml
single handed:
  katanas: weapons/katanas.yml
  daggers: weapons/daggers.yml
  wands: weapons/wands.yml
